# Initial Exploration: Correlation and Visualization

We have a data set of almost 180.000 campaigns. The data set has mostly (but not completely) been cleaned. Data for 100.000 projects  Download 100.000 projects(training set) is provided to you with information of whether the project was completely funded (succeeded) or not. For the remaining 78.065 projects  Download 78.065 projects(test set) the funding status is withheld. Your assignment is to train a model that will predict the funding status of the remaining projects. You will hand in these predictions, and then we can check how well your model did.

The grading of your project, however, does not depend on the quality of your model, it depends on how well you can explain what you did and why. 
You will show this in a presentation in the last week of the course. 

Funded, what determines it?

Predict funding status of the remaining projects.


In [40]:
import pandas as pd
import seaborn as sns
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

from matplotlib.pylab import rcParams
rcParams['figure.figsize'] = 16, 8

from scipy.stats import norm
from scipy import stats

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

import warnings
warnings.filterwarnings('ignore')

While exploring the data we have understood that the delimeter is a komma, which result in unstructured visual representation of the excel file.

first we check if the deadline or start date had any correlation at all with funding, this was not the case. Furthermore we also tried and see if the funding goal had any effect, this also was not the case. Hence the quantitative data where we have our hands on do not correlate with the funding success

Which ones could introduce bias? What bias exactly?


Linear regression to find correlation
Logistic regression to find ocrrelation between multiple data for true or false classification
check mode for categorical data?


transform datestamp to datetime



In [172]:
df = pd.read_csv (r'./KS_model_training_data.csv', sep = ',')

df = df[df['project_id'].astype(str).str.startswith('KS_')]
df = df.fillna('')
backers_count = df['backers_count'].describe()
category = df['category'].describe()
df["funded"].replace({"TRUE": "True", "False": "False"}, inplace=True)
funded = df['funded'].describe()

print(np.corrcoef(df['funded'], df['goal']))
print(np.corrcoef(df['funded'], df['created_at']))
print(np.corrcoef(df['funded'], df['deadline']))
print(np.corrcoef(df['funded'], df['staff_pick']))

# df['category'].value_counts()[:20].plot(kind='bar')
# df.plot.scatter(x = 'goal', y ='category')



[[ 1.         -0.03269242]
 [-0.03269242  1.        ]]
[[ 1.         -0.27365083]
 [-0.27365083  1.        ]]
[[ 1.         -0.27260388]
 [-0.27260388  1.        ]]
[[1.         0.25352449]
 [0.25352449 1.        ]]


https://pbpython.com/categorical-encoding.html
We tried to use labelencoding to give categorical values a code with wich we can then see if there is any correlation between categories and funding.

In [ ]:

df["category"] = df["category"].astype('category')
df["category_encoded"] = df["category"].cat.codes

df["subcategory"] = df["subcategory"].astype('category')
df["subcategory_encoded"] = df["subcategory"].cat.codes


df["location"] = df["location"].astype('category')
df["location_encoded"] = df["location"].cat.codes


df["country"] = df["country"].astype('category')
df["country_encoded"] = df["country"].cat.codes

df['blurb_length'] = df['blurb'].str.len()
df['name_length'] = df['name'].str.len()


print(df["category_encoded"])


print(np.corrcoef(df['funded'], df['category_encoded']))
print(np.corrcoef(df['funded'], df['subcategory_encoded']))
print(np.corrcoef(df['funded'], df['location_encoded']))
print(np.corrcoef(df['funded'], df['country_encoded']))
print(np.corrcoef(df['funded'], df['blurb_length']))
print(np.corrcoef(df['funded'], df['fx_rate']))
print(np.corrcoef(df['funded'], df['name_length']))

